notifications:
    email: false

dist: focal

sudo: false

language: python

matrix:
    fast_finish: true

cache:
    - pip

python:
    - '3.8'


before_install:
    - travis_retry pip install --upgrade pip setuptools py
    - "travis_retry pip install twine wheel coveralls"
    - pip install poetry
    - cat poetry.lock
    - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.2-amd64.deb -o elasticsearch.deb
    - sudo dpkg -i --force-confnew elasticsearch.deb
    - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
    - sudo service elasticsearch restart

install:
    - "travis_retry poetry install --extras tests"

before_script:
  - sleep 10

script:
    - "./run-tests.sh"

after_success:
    - coveralls


